# Generated by Django 5.0.1 on 2024-02-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('loginapproval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='leaverequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('days', models.IntegerField()),
                ('reason', models.CharField(max_length=200, null=True)),
                ('leaveapproved', models.BooleanField(default=False)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='leaveapp.student')),
            ],
        ),
    ]
